version: '3.6'

services:
  instabot:
    image: cupcakearmy/instabot
    restart: always
    container_name: instabot
    volumes:
      # To reset the DB delete and create the data.db file
      # rm data.db; touch data.db;
      # or
      # cat /dev/null > data.db
      - ./data.db:/app/follows_db.db
      - ./config.json:/app/config.json:ro