version: '3'

services:
  instabot:
    image: cupcakearmy/instabot
    restart: always
    container_name: instabot
    volumes:
      - ./data.db:/app/data.db
      - ./config.json:/app/config.json:ro