version: '3.6'

services:
  instabot:
    build: ./bot
    restart: always
    container_name: instabot
    volumes:
      # Uncomment if you want to save the db.
      # In that case run `touch data.db` before running the container!
      # - ./data.db:/app/follows_db.db
      - ./config.json:/app/config.json:ro