FROM alpine

WORKDIR /app

RUN apk add --no-cache git python3
RUN git clone https://github.com/instabot-py/instabot.py.git .
RUN python3 -m pip install --no-cache-dir -r requirements.txt

COPY ./app.py .

CMD [ "python3", "-u", "./app.py" ]