FROM alpine:3.7

WORKDIR /app

RUN apk add --no-cache python3
RUN python3 -m pip install --upgrade pip

COPY ./requirements.txt .
RUN	python3 -m pip install --no-cache-dir -r requirements.txt

COPY ./ .

CMD [ "python3", "-u", "./app.py" ]